version: '3.9'

services:
  check-sitemap-workspace:
    container_name: check-sitemap-workspace
    build:
      context: ./php-fpm
    env_file:
     - ./.env
    user: "${UID}:${GID}"
    ports:
      - '9000:9000'
    volumes:
      - ../:/var/www/
      - ./php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./php-fpm/conf.d/custom_php.ini:/usr/local/etc/php/conf.d/custom_php.ini
    environment:
      XDEBUG_MODE: debug
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - check_sitemap_net

  check-sitemap-nginx:
    container_name: check-sitemap-nginx
    build:
      context: ./nginx
    volumes:
      - ../:/var/www/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
    ports:
      - '80:80'
    networks:
      - check_sitemap_net
    depends_on:
      - check-sitemap-workspace


networks:
  check_sitemap_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 176.0.0.0/16
          ip_range: 176.0.0.0/24
          gateway: 176.0.0.1
